name = "TimeSeriesClassification"
uuid = "4869f98a-92d2-4a27-bbf6-5599fe134177"
authors = ["Antonín Kříž (https://www.antoninkriz.eu)"]
version = "1.0.0"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
CategoricalDistributions = "af321ab8-2d2e-40a6-b165-3d674595d28e"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
VectorizedStatistics = "3b853605-1c98-4422-8364-4bd93ee0529e"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
CategoricalArrays = "^0.10.8"
CategoricalDistributions = "^0.1.10"
LoopVectorization = "^0.12.165"
MLJBase = "^1.0.0"
MLJModelInterface = "^1.9.1"
ProgressMeter = "^1.7.2"
StaticArrays = "^1.6.2"
VectorizedStatistics = "^0.5.5"
ZipFile = "^0.10.1"
julia = "^1.9.2"

[extras]
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["MLJBase", "Test"]
