name = "TsClassification"
uuid = "4869f98a-92d2-4a27-bbf6-5599fe134177"
authors = ["Antonín Kříž (https://www.antoninkriz.eu)"]
version = "0.1.0"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ScientificTypesBase = "30f210dd-8aff-4c5f-94ba-8e64358c1161"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
MLJModelInterface = "^1.8.0"
StaticArrays = "^1.5.16"
julia = "^1.8.5"

[extras]
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["MLJ", "Test"]
